name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-privacy.txt ]; then pip install -r requirements-privacy.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting with black
      run: |
        black --check --diff .
    
    - name: Check imports with isort
      run: |
        isort --check --diff .
    
    - name: Build Docker image
      run: |
        docker build -t private-ai-proxy:test .
        docker build -f Dockerfile.proxy -t private-ai-proxy-only:test .
    
    - name: Verify Docker image
      run: |
        docker run --rm private-ai-proxy:test python -c "import app; print('App imported successfully')"
        docker run --rm private-ai-proxy-only:test python -c "import ai_proxy; print('AI Proxy imported successfully')"